export function handleException(status) {
    alert('파일 따로 만들어서 exception 처리', status);
}